import 'tarot_models.dart';

class _MinorSuit {
  final String id;
  final String nameTr;
  final String nameEn;
  final String tag;

  const _MinorSuit({
    required this.id,
    required this.nameTr,
    required this.nameEn,
    required this.tag,
  });
}

class _MinorRank {
  final String id;
  final String nameTr;
  final String nameEn;
  final List<String> tags;

  const _MinorRank({
    required this.id,
    required this.nameTr,
    required this.nameEn,
    required this.tags,
  });
}

const List<TarotCard> _majorCardsTr = [
  TarotCard(
    id: 'major_00_fool',
    nameTr: 'Deli',
    nameEn: 'The Fool',
    tags: ['başlangıç', 'risk', 'özgürlük'],
  ),
  TarotCard(
    id: 'major_01_magician',
    nameTr: 'Büyücü',
    nameEn: 'The Magician',
    tags: ['niyet', 'beceri', 'odak'],
  ),
  TarotCard(
    id: 'major_02_high_priestess',
    nameTr: 'Başrahibe',
    nameEn: 'The High Priestess',
    tags: ['sezgi', 'sır', 'içgörü'],
  ),
  TarotCard(
    id: 'major_03_empress',
    nameTr: 'İmparatoriçe',
    nameEn: 'The Empress',
    tags: ['bereket', 'şefkat', 'yaratıcılık'],
  ),
  TarotCard(
    id: 'major_04_emperor',
    nameTr: 'İmparator',
    nameEn: 'The Emperor',
    tags: ['otorite', 'yapı', 'koruma'],
  ),
  TarotCard(
    id: 'major_05_hierophant',
    nameTr: 'Başrahip',
    nameEn: 'The Hierophant',
    tags: ['gelenek', 'öğreti', 'inanç'],
  ),
  TarotCard(
    id: 'major_06_lovers',
    nameTr: 'Aşıklar',
    nameEn: 'The Lovers',
    tags: ['seçim', 'uyum', 'ilişki'],
  ),
  TarotCard(
    id: 'major_07_chariot',
    nameTr: 'Savaş Arabası',
    nameEn: 'The Chariot',
    tags: ['irade', 'kontrol', 'ilerleme'],
  ),
  TarotCard(
    id: 'major_08_strength',
    nameTr: 'Güç',
    nameEn: 'Strength',
    tags: ['cesaret', 'sabır', 'şefkat'],
  ),
  TarotCard(
    id: 'major_09_hermit',
    nameTr: 'Ermiş',
    nameEn: 'The Hermit',
    tags: ['içe dönüş', 'bilgelik', 'ara'],
  ),
  TarotCard(
    id: 'major_10_wheel',
    nameTr: 'Kader Çarkı',
    nameEn: 'Wheel of Fortune',
    tags: ['döngü', 'şans', 'değişim'],
  ),
  TarotCard(
    id: 'major_11_justice',
    nameTr: 'Adalet',
    nameEn: 'Justice',
    tags: ['denge', 'karar', 'dürüstlük'],
  ),
  TarotCard(
    id: 'major_12_hanged_man',
    nameTr: 'Asılan Adam',
    nameEn: 'The Hanged Man',
    tags: ['bekleme', 'teslimiyet', 'bakış'],
  ),
  TarotCard(
    id: 'major_13_death',
    nameTr: 'Ölüm',
    nameEn: 'Death',
    tags: ['dönüşüm', 'bitiş', 'yenilenme'],
  ),
  TarotCard(
    id: 'major_14_temperance',
    nameTr: 'Denge',
    nameEn: 'Temperance',
    tags: ['uyum', 'ölçü', 'şifa'],
  ),
  TarotCard(
    id: 'major_15_devil',
    nameTr: 'Şeytan',
    nameEn: 'The Devil',
    tags: ['bağlılık', 'gölge', 'tutku'],
  ),
  TarotCard(
    id: 'major_16_tower',
    nameTr: 'Kule',
    nameEn: 'The Tower',
    tags: ['sarsıntı', 'gerçek', 'özgürleşme'],
  ),
  TarotCard(
    id: 'major_17_star',
    nameTr: 'Yıldız',
    nameEn: 'The Star',
    tags: ['umut', 'ilham', 'iyileşme'],
  ),
  TarotCard(
    id: 'major_18_moon',
    nameTr: 'Ay',
    nameEn: 'The Moon',
    tags: ['belirsizlik', 'rüya', 'sezgi'],
  ),
  TarotCard(
    id: 'major_19_sun',
    nameTr: 'Güneş',
    nameEn: 'The Sun',
    tags: ['neşe', 'açıklık', 'başarı'],
  ),
  TarotCard(
    id: 'major_20_judgement',
    nameTr: 'Yargı',
    nameEn: 'Judgement',
    tags: ['uyanış', 'çağrı', 'hesap'],
  ),
  TarotCard(
    id: 'major_21_world',
    nameTr: 'Dünya',
    nameEn: 'The World',
    tags: ['tamamlanma', 'bütünlük', 'kutlama'],
  ),
];

const List<_MinorSuit> _minorSuitsTr = [
  _MinorSuit(
    id: 'wands',
    nameTr: 'Değnek',
    nameEn: 'Wands',
    tag: 'tutku',
  ),
  _MinorSuit(
    id: 'cups',
    nameTr: 'Kupa',
    nameEn: 'Cups',
    tag: 'duygu',
  ),
  _MinorSuit(
    id: 'swords',
    nameTr: 'Kılıç',
    nameEn: 'Swords',
    tag: 'zihin',
  ),
  _MinorSuit(
    id: 'pentacles',
    nameTr: 'Tılsım',
    nameEn: 'Pentacles',
    tag: 'madde',
  ),
];

const List<_MinorRank> _minorRanksTr = [
  _MinorRank(
    id: 'ace',
    nameTr: 'As',
    nameEn: 'Ace',
    tags: ['başlangıç', 'potansiyel'],
  ),
  _MinorRank(
    id: 'two',
    nameTr: 'İki',
    nameEn: 'Two',
    tags: ['denge', 'seçim'],
  ),
  _MinorRank(
    id: 'three',
    nameTr: 'Üç',
    nameEn: 'Three',
    tags: ['büyüme', 'işbirliği'],
  ),
  _MinorRank(
    id: 'four',
    nameTr: 'Dört',
    nameEn: 'Four',
    tags: ['stabilite', 'temel'],
  ),
  _MinorRank(
    id: 'five',
    nameTr: 'Beş',
    nameEn: 'Five',
    tags: ['sınav', 'çatışma'],
  ),
  _MinorRank(
    id: 'six',
    nameTr: 'Altı',
    nameEn: 'Six',
    tags: ['uyum', 'geçiş'],
  ),
  _MinorRank(
    id: 'seven',
    nameTr: 'Yedi',
    nameEn: 'Seven',
    tags: ['strateji', 'değerlendirme'],
  ),
  _MinorRank(
    id: 'eight',
    nameTr: 'Sekiz',
    nameEn: 'Eight',
    tags: ['hareket', 'hız'],
  ),
  _MinorRank(
    id: 'nine',
    nameTr: 'Dokuz',
    nameEn: 'Nine',
    tags: ['dayanıklılık', 'olgunluk'],
  ),
  _MinorRank(
    id: 'ten',
    nameTr: 'On',
    nameEn: 'Ten',
    tags: ['tamamlanma', 'yük'],
  ),
  _MinorRank(
    id: 'page',
    nameTr: 'Prens',
    nameEn: 'Page',
    tags: ['merak', 'haber'],
  ),
  _MinorRank(
    id: 'knight',
    nameTr: 'Şövalye',
    nameEn: 'Knight',
    tags: ['ivme', 'cesaret'],
  ),
  _MinorRank(
    id: 'queen',
    nameTr: 'Kraliçe',
    nameEn: 'Queen',
    tags: ['ustalık', 'şefkat'],
  ),
  _MinorRank(
    id: 'king',
    nameTr: 'Kral',
    nameEn: 'King',
    tags: ['liderlik', 'otorite'],
  ),
];

final List<TarotCard> tarotCardsTr = [
  ..._majorCardsTr,
  for (final suit in _minorSuitsTr)
    for (final rank in _minorRanksTr)
      TarotCard(
        id: '${suit.id}_${rank.id}',
        nameTr: '${suit.nameTr} ${rank.nameTr}',
        nameEn: '${rank.nameEn} of ${suit.nameEn}',
        tags: [...rank.tags, suit.tag],
      ),
];

const List<String> tarotIntrosTr = [
  'Bu açılım, günün enerjisini sakin bir mercekle görmeni ve küçük ama net bir niyet belirlemeni istiyor.',
  'Kartlar, bugün dikkatini dağıtan gürültüden sıyrılıp öz mesajı duyman için bir harita sunuyor.',
  'Şu anki akış, ince işaretlerle konuşuyor; bu okuma, o işaretleri düzenli bir sıraya yerleştiriyor.',
  'Açılımın tonu sakin ama net; adımların nereye yönelmesi gerektiğini gösteren küçük işaretler var.',
  'Bugünün mesajı, kısa bir duraklama ve odaklı bir bakış istiyor; niyetini sadeleştirmen önemli.',
  'Kartlar, kendine dürüst bir alan açmanı ve iç sesini hafifçe yükseltmeni öneriyor.',
  'Bu okuma, hız yerine farkındalığı seçtiğinde önünün nasıl açıldığını göstermek için geldi.',
  'Şimdi konuşan şey, büyük sözlerden çok küçük ayrıntılar; kartlar o ayrıntıları büyütüyor.',
  'Açılım, bugünün dalgasında nerede durman gerektiğini ve hangi rüzgara güvenebileceğini fısıldıyor.',
  'Kartlar, zihnini sadeleştirip kalbini netleştirmen için bir denge noktası çiziyor.',
  'Bu okumada, geçmişin izi ve bugünün ihtiyacı aynı çerçevede buluşuyor; dikkatli bir seçim zamanı.',
  'Kartlar, bugün için tek bir cümlelik niyetin tüm akışı toparlayabileceğini hatırlatıyor.',
  'Açılımın kapısı, küçük bir cesaretle açılıyor; içeri girdiğinde tablo daha anlaşılır olacak.',
  'Bugünün sesi yumuşak ama kararlı; kartlar bu sesi somutlaştırıp yönünü işaret ediyor.',
  'Kartlar, olanı yargılamadan görmeni ve bundan sonra neyi besleyeceğini seçmeni istiyor.',
  'Bu açılım, karmaşık hislerin içinde net bir çizgi bulman için rehberlik ediyor.',
  'Açılım, bir adım geri çekilip büyük resmi görmeni, sonra da en küçük doğru adımı seçmeni söylüyor.',
  'Kartların dili bugün sade: az ama etkili bir hareket, büyük bir düğümü çözüyor.',
  'Şu anın mesajı, sabırlı bir odak ve net bir karar talep ediyor; kartlar bunu görünür kılıyor.',
  'Bu okuma, içgörü ile eylem arasında köprü kurmanı ve gereksiz ağırlıkları bırakmanı öneriyor.',
  'Kartlar, zihnini dağıtan fazlalıkları azaltıp öz değeri öne çıkarmak için bir ışık tutuyor.',
  'Açılım, bugünün ritmini yakalayıp onu bozmadan yönünü düzeltmen için sakin bir rehber.',
  'Bugünün mesajı, içsel bir netlik arıyor; kartlar bunu küçük ama tutarlı işaretlerle sunuyor.',
  'Kartlar, niyetini tazelemeni ve günün içinde görünmeyeni fark etmeni sağlayacak bir pencere açıyor.',
];

const List<String> tarotClosingsTr = [
  'Kapanışta, tek bir küçük adım seç ve onu bugün bitir; ilerleme, süreklilikten doğar.',
  'Günün sonunda, duygularını kısa notlarla yaz; böylece mesajı somutlaştırıp yarına taşırsın.',
  'Bu yorumun özü, yumuşak ama net bir sınır koymak; sınır koydukça enerji toparlanır.',
  'Şimdi en iyi tavsiye, acele etmeden karar vermek ve iç sesini duyana kadar beklemektir.',
  'Bir konuya fazla yükleniyorsan, yükü parçalara ayır; her parça ayrı bir çözüm bulur.',
  'Küçük bir düzenleme, büyük bir rahatlama getirir; bugün sadece bir şeyi sadeleştir.',
  'Kalbini daraltan şeyi fark edip adlandır; adı konan yük, hafifler ve yön verir.',
  'Bugün, sözünü kısa ve net tut; fazla açıklama yerine tutarlılık güven yaratır.',
  'Kapanış mesajı şudur: Bir şeyi bitir, bir şeyi bırak, bir şeyi başlat.',
  'Niyetini bir cümleye indir; o cümle gün boyu pusulan olsun.',
  'Harekete geçmeden önce derin bir nefes al; sakin zihin daha temiz seçim yapar.',
  'Küçük bir teşekkür ritüeli, enerjini toparlar; minnettarlık akışı hızlandırır.',
  'Günün sonunda, öğrendiğin tek bir dersi not al; bu, yarının anahtarı olur.',
  'Gereksiz açıklamalar yerine, yaptığın şeye sadık kal; sadakat istikrar doğurur.',
  'Süreci kontrol etmek yerine, niyeti net tut; kontrol yerine odak güç verir.',
  'Bir adım at, ardından kısa bir duraklama yap; ritim dengede kalır.',
  'Bugün bir kişiye açık ve nazik bir söz söyle; ilişkiyi temizler ve alan açar.',
  'Kapanışta, zihnini sakinleştiren bir rutin seç; rutin, güvenli bir zemin sağlar.',
  'Çok seçenek arasında kayboluyorsan, en basit olanı seç; sadelik sana yol gösterir.',
  'Bu okuma, küçük bir cesaretin büyük rahatlama getireceğini söylüyor; o cesareti seç.',
  'Kısa bir yürüyüş ya da su içmek bile enerjiyi değiştirir; bedeni unutma.',
  'Bugün, istemediğin şeye kibarca hayır de; sınır çizmek huzuru büyütür.',
  'Kapanış tavsiyesi: Bir işi tamamlamadan diğerine geçme; sonuç, dağınıklığı azaltır.',
  'Önüne çıkan işareti gör ve küçük bir deney yap; deneme, bilgeliğin kapısıdır.',
  'Duygun yoğunlaşırsa, üç derin nefesle alan aç; ardından tek bir net cümle kur.',
  'Sözlerin kadar eylemin de net olsun; uyum, içsel güveni büyütür.',
  'Kendini yargılamak yerine gözlemle; gözlem, doğru hamleyi seçtirir.',
  'Bugün bir şeyi düzenle, bir şeyi paylaş, bir şeyi dinlendir; denge böyle kurulur.',
  'Kapanışta, basit bir plan yap ve ona sadık kal; plan, dalgayı sakinleştirir.',
  'Günün mesajı kapanıyor: Küçük bir adım, büyük bir kapıyı aralar.',
  'Şimdi sessiz bir alan yarat ve kararını orada ver; sessizlik netliği getirir.',
  'Bir kez daha niyetini hatırla; niyet net olursa sonuç kendiliğinden toparlanır.',
];

const Map<TarotArea, List<String>> tarotAreaLinesTr = {
  TarotArea.love: [
    'Aşk alanında, açık iletişim ve küçük bir dürüstlük adımı ilişkideki düğümü çözer.',
    'Kalbini korurken yumuşak kalmak mümkün; bugün beklentini net söylemek yakınlığı artırır.',
    'İlişkide güven, küçük ama tutarlı davranışlarla büyür; sözü eylemle desteklemek önemli.',
    'Yeni bir tanışma enerjisi varsa, acele etme; yavaşlık, gerçek uyumu gösterir.',
    'Geçmiş kırgınlıklar gündeme gelirse, suçlamak yerine hisleri adlandır; bu, iyileşmeyi başlatır.',
    'Aşk tarafında sınırların belirsizleşmiş olabilir; nazik ama net bir çizgi çizmek iyi gelir.',
    'Bugün, sevgide karşılıklılık temasına dikkat et; tek taraflı çaba enerji kaybettirir.',
    'Romantik bir jest, büyük sözlerden daha etkili olabilir; küçük bir somut adım seç.',
    'İlişkide sabır ve merak birlikte çalışıyor; soru sormak, yanlış anlamayı azaltır.',
    'Kalp alanında, beklentini sadeleştir; sade beklenti, hayal kırıklığını azaltır.',
    'Eğer yalnızsan, kendine verdiğin değeri yükselt; bu, yeni bağlantıları daha sağlıklı çeker.',
    'Aşk konusunda, bugün bir konuşmayı net ve kısa tutmak, duygusal yükü hafifletir.',
  ],
  TarotArea.money: [
    'Para alanında, küçük bir bütçe düzenlemesi büyük rahatlama sağlar; bugün tek kalemi gözden geçir.',
    'Gelir gider dengesini sadeleştir; gereksiz bir harcamayı durdurmak akışı toparlar.',
    'Maddi konularda planlı ilerlemek, fırsatı görünür kılar; kısa bir liste yap.',
    'Bugün, güvenli bir adım tercih et; hızlı kazanç yerine sürdürülebilir ilerleme kazandırır.',
    'Parayla ilgili bir karar erteledinse, net bir tarih koy; belirsizlik maliyeti büyütür.',
    'Maddi bir konuda destek istemek zayıflık değildir; doğru kişiyle konuşmak yükü azaltır.',
    'Küçük bir birikim hedefi belirle; hedef, harcamayı disipline eder.',
    'Kaynaklarını gözden geçir ve fazlalığı ayıkla; sadeleşme, nakit akışını rahatlatır.',
    'Bugün, finansal bir konuda sezgini dinle ama veriyi de kontrol et; denge korur.',
    'Maddi hedeflerde sabır önemli; istikrarlı adım, dalgalanmaları dengeler.',
    'Emeğinin karşılığını istemekten çekinme; değerini net ifade etmek akışı iyileştirir.',
    'Para alanında, küçük bir pazarlık ya da teklif iyileştirmesi fırsat yaratır.',
  ],
  TarotArea.career: [
    'Kariyerde görünürlük zamanı; küçük bir başarıyı paylaşmak yeni fırsatların kapısını açar.',
    'İş tarafında netlik kazanmak için, bugün tek bir öncelik seç ve onu bitir.',
    'Ekip içinde iletişimi temiz tut; kısa ve net bir mesaj, yanlış anlaşılmayı azaltır.',
    'Yeni bir görev için hazır hissediyorsun; ama kapsamı netleştirerek başlaman daha sağlam olur.',
    'Kariyerde ilerleme, tutarlılıkla gelir; küçük ama düzenli adımlar güven oluşturur.',
    'Bugün, işteki sınırlarını belirlemek önemli; fazla yük almak verimi düşürür.',
    'Bir öğrenme fırsatı çıkabilir; kısa bir eğitim ya da not, uzun vadede değer katar.',
    'İş alanında strateji şart; haftalık hedefini yazmak odak sağlar.',
    'Kariyerde yön değişikliği düşünüyorsan, küçük bir deneme yap; deneyim netlik getirir.',
    'Geri bildirim almaktan kaçınma; yapıcı yorum, performansı güçlendirir.',
    'Başladığın bir işi tamamlamak, güvenini büyütür; bugün kapanışa odaklan.',
    'İş ilişkilerinde saygı ve tutarlılık belirleyici; sözünü tutmak alanını sağlamlaştırır.',
  ],
  TarotArea.mood: [
    'Ruh halinde dalgalanma varsa, bedeninle temas kur; kısa bir yürüyüş zihni sakinleştirir.',
    'Bugün, duygularını bastırmak yerine adlandır; isim verilen duygu yumuşar.',
    'Kendi sınırlarına saygı göstermek ruh halini dengeler; hayır demek bir iyileşmedir.',
    'Zihnin dağınıksa, küçük bir düzenleme yap; dış düzen iç düzeni destekler.',
    'Ruh halini yükseltmek için bir minik ritüel seç; sıcak bir içecek bile yeter.',
    'İç dünyanda gerginlik hissediyorsan, nefese dön; üç derin nefes genişlik sağlar.',
    'Bugün, kendine karşı nazik ol; iç eleştiriyi biraz kısınca enerji toparlanır.',
    'Duygusal yoğunluk, yaratıcılık için yakıt olabilir; bunu küçük bir üretime dönüştür.',
    'Ruh halin düşükse, iletişim kurmak iyi gelebilir; bir kişiyle kısa bir sohbet yeter.',
    'Kendine kısa bir molayı hak gör; dinlenmek, ilerlemenin parçasıdır.',
    'Sakinlik ihtiyacın artmış; telefon ve bildirimleri azaltmak zihni temizler.',
    'Bugün, duygusal denge için küçük bir hedef belirle; hedef, yön verir.',
  ],
};

const List<String> tarotFallbackCardGeneralLinesTr = [
  'günlük akışta küçük ama etkili bir ders taşır; dikkatini ayrıntılara çekmek istiyor.',
  'bu kart, basit görünen bir konunun aslında yön belirlediğini söyler; sabırlı ol.',
  'ilerleme için pratik bir adım önerir; düzen kurmak şimdi faydalı.',
  'düşünce ve eylem arasında denge arar; acele yerine ölçü seç.',
  'küçük bir seçim büyük etki yaratabilir; bugün netlik önemlidir.',
  'enerjini tek bir noktaya topladığında sonuç hızlanır; dağılma.',
  'bu işaret, günlük ritmini sadeleştirmeni ister; sadeleşme rahatlatır.',
  'sorumluluklarını düzenlemek için doğru zaman; ufak bir plan yeter.',
  'bu kart, bir sürecin olgunlaşmasını vurgular; sabırla ilerle.',
  'dış koşullar değişse de iç tutarlılık seni korur; niyetini net tut.',
  'küçük bir destek ya da işbirliği fark yaratabilir; yardım istemek güçtür.',
  'sonuç almak için istikrar gerekir; bugün bir alışkanlığı güçlendirmek iyi olur.',
];

const Map<String, List<String>> tarotCardGeneralLinesTr = {
  'major_00_fool': [
    'yeni bir başlangıcın heyecanını ve bilinmeze güvenmeyi anlatır; küçük bir risk, kapı açar.',
    'özgür ruhun hareketini ve plansız ama cesur bir adımı vurgular; merak bugün rehberindir.',
    'korkuyu hafifletip denemeye davet eder; ilk adım kusursuz değil, yeterince samimi olmalı.',
    'beklenmedik bir fırsatın geldiğini söyler; fazla hesap yapmak yerine yolun kendisine güven.',
    'sadeleşip yükleri bırakman gerektiğini hatırlatır; hafifledikçe yol görünür olur.',
    'masum bir bakış ve taze bir niyet taşır; bu, yeni bir sayfanın açıldığını gösterir.',
    'hayatın sürprizlerini kabul etmenin önemini söyler; kontrol yerine esneklik güç verir.',
    'deneyim kazanmanın en hızlı yolu denemektir; bugünkü cesaret, yarının bilgisini getirir.',
  ],
  'major_01_magician': [
    'niyetini somutlaştırma gücünü anlatır; elindeki kaynaklar düşündüğünden daha yeterli.',
    'odaklı irade ve becerinin birleştiğini söyler; doğru araçla doğru hamle gelir.',
    'bugün, düşünceyi eyleme çevirme zamanıdır; küçük bir başlangıç büyük etki yaratır.',
    'iletişim ve ifade gücün yükseliyor; mesajını netleştirirsen kapılar açılır.',
    'kontrol senin elinde; dikkatini tek noktaya topladığında sonuç hızlanır.',
    'yeteneklerini hatırlatır ve gösterme cesareti verir; saklı kalan güç kullanılmak ister.',
    'fikirlerinle gerçeği şekillendirebilirsin; niyetini temiz tutmak sonuçları berraklaştırır.',
    'şimdi konuşmak ve harekete geçmek etkili; zamanlama lehine akıyor.',
  ],
  'major_02_high_priestess': [
    'iç sesin bugün daha yüksek; dış gürültüden çok sezgine kulak ver.',
    'gizli kalan bilgilerin yavaşça açıldığını söyler; sabır, gerçeği görünür kılar.',
    'duygu ve sezgi dengesi istiyor; hızlı karar yerine içsel onay beklenmeli.',
    'gözle görülmeyen işaretler yoğun; rüyalar ve hisler mesaj taşıyabilir.',
    'içe dönmek ve sessizlikte kalmak şifa getirir; cevaplar içeride saklı.',
    'bugün her şeyi paylaşmak değil, sakince gözlemlemek daha doğru olabilir.',
    'bilinmeyeni kabul etme çağrısıdır; netlik, zamanla ve sakinlikle gelir.',
    'sezgiyle hareket edersen daha sağlam ilerlersin; mantık yalnız kalmamalı.',
  ],
  'major_03_empress': [
    'bereket ve üretkenliği vurgular; beslediğin şey hızla büyümeye hazır.',
    'şefkatli bir yaklaşımın kapıları açacağını söyler; yumuşaklık güçtür.',
    'yaratıcılık akıyor; küçük bir fikir bile bugün somut bir ürüne dönüşebilir.',
    'kendine iyi bakmak başarıyı destekler; bedenin ve ruhun birlikte çalışmalı.',
    'doğal akışa güvenmeyi hatırlatır; acele yerine bakım ve sabır öne çıkar.',
    'ev ve yuva teması güçlenir; güvenli alan yaratmak sana iyi gelecek.',
    'paylaşma ve cömertlik enerji getirir; verdiğin ölçüde çoğalırsın.',
    'zihnini yoran şeyi yumuşat; şefkat, karmaşayı sadeleştirir.',
  ],
  'major_04_emperor': [
    'yapı kurma ve düzeni sağlamlaştırma çağrısıdır; net sınırlar güven verir.',
    'kontrolü eline alman gerektiğini söyler; planlı adım, belirsizliği azaltır.',
    'sorumluluk almak bugün güç kazandırır; liderlik, kararlılıkla büyür.',
    'kurallar ve çerçeve faydalı; dağınık süreçleri sistemleştir.',
    'disiplinin getirdiği rahatlık öne çıkar; düzen kurdukça enerji toplanır.',
    'otorite figürleriyle ilişkiler önem kazanır; saygı ve netlik işini kolaylaştırır.',
    'uzun vadeli bir plan yapmanın zamanı; kısa vadeli hevesleri dengele.',
    'güvenli bir temel atmak istiyorsun; adım adım ilerlemek başarıyı getirir.',
  ],
  'major_05_hierophant': [
    'geleneksel bir yolun işe yaradığını gösterir; denenmiş yöntemler bugün destek olur.',
    'öğrenme ve rehberlik teması güçlenir; bir öğretmene ya da kaynağa başvur.',
    'değerlerini netleştirmek önemli; inancın ve davranışın uyumlanmalı.',
    'topluluk ve aidiyet vurgusu var; destek almak yalnızlığını azaltır.',
    'kurallara saygı, düzen getirir; sınır çizmek sana güven sağlar.',
    'ritüel ya da rutin, zihni sakinleştirir; küçük bir uygulama bile etkilidir.',
    'sözünde durmak ve etik davranmak bugün öne çıkar; güven böyle kazanılır.',
    'gelenek ile yenilik arasında denge kurman gerekiyor; kökler, yönü belirler.',
  ],
  'major_06_lovers': [
    'kalp ve zihin arasında bir seçim zamanı; değerlerinle uyumlu olanı seç.',
    'ilişkide uyum ve karşılıklılık vurgulanır; açık iletişim bağı güçlendirir.',
    'çekim artıyor; ancak net bir karar vermek gerekiyor.',
    'ortak bir yol bulmak mümkün; uzlaşma, güveni büyütür.',
    'aşk kadar seçim de bu kartın temasıdır; ertelemek yerine netlik getir.',
    'duygusal bağ derinleşebilir; samimiyet, şüpheyi azaltır.',
    'iki seçenek arasında kalmış olabilirsin; kalbinin sesi yön gösterir.',
    'paylaşılan değerler ön planda; benzer hedefler ilişkiyi sağlamlaştırır.',
  ],
  'major_07_chariot': [
    'irade ve kararlılık seni öne taşıyor; yönünü belirleyip hızlanabilirsin.',
    'zıt güçleri dengelemek gerekiyor; kontrolü eline aldığında ilerleme gelir.',
    'başarı, disiplinli bir hamleyle mümkün; odak, dağınıklığı toplar.',
    'yola çıkma enerjisi yüksek; kararlı durursan engeller azalır.',
    'hedefe kilitlenmişsin; kısa bir plan, gücünü doğru yere yönlendirir.',
    'bugün, cesur bir hareketin karşılığını görme ihtimali artıyor.',
    'sınırları net çizip yönü belirlemek önemli; kararsızlık hızını düşürür.',
    'mücadeleyi korku değil irade yönetmeli; kontrol, sakin bir güçtür.',
  ],
  'major_08_strength': [
    'şefkatli bir güç kullanman gerekiyor; yumuşak yaklaşım daha etkili.',
    'içsel cesaret yükseliyor; sakin ama kararlı kalırsan sonuç gelir.',
    'sabır, bugün en büyük kuvvet; acele etmeden ilerlemek faydalı.',
    'duyguları bastırmak yerine yönetmek önem kazanır; nazik bir disiplin işe yarar.',
    'kendi korkunla yüzleşmen bekleniyor; yüzleşme, özgürlük getirir.',
    'güç, baskı değil denge demektir; yumuşaklığın içinde sağlamlık var.',
    'içsel güveni beslemek bugün etkili; kendine inanmak kapı açar.',
    'direnci sevgiyle dönüştürmek mümkün; yaklaşımın tonu sonucu belirler.',
  ],
  'major_09_hermit': [
    'içe dönüş ve yalnız kalma ihtiyacı vurgulanır; sessizlik netliği getirir.',
    'bilgeliği dışarıda değil içeride araman gerektiğini söyler.',
    'hızlı karar yerine düşünmek önemli; kısa bir geri çekilme fayda sağlar.',
    'kendi ışığını görme zamanı; başkalarının sesi yerine iç sese dön.',
    'dinlenme ve sadeleşme, zihni güçlendirir; bugün kalabalıklar yorabilir.',
    'gerçeği ararken sabırlı ol; cevaplar ağır ama sağlam gelir.',
    'gözlemle ve not al; küçük detaylar büyük resmi gösterecek.',
    'tek başına yürümek korkutmasın; bu yalnızlık, olgunlaşma sürecidir.',
  ],
  'major_10_wheel': [
    'döngü değişiyor; beklenmedik bir fırsat ya da yön değişimi ortaya çıkabilir.',
    'şans kapısı açılabilir; hazırlıklı olursan akış seni destekler.',
    'iniş çıkışlar doğal; akışa direnmek yerine yönünü ayarla.',
    'bugün, tesadüf gibi görünen bir işaret önemli olabilir; küçük ayrıntıları kaçırma.',
    'kaderin çarkı dönüyor; değişim kaçınılmaz ve öğretici.',
    'kontrol edemediğin şeylere takılma; esneklik seni güçlü kılar.',
    'değişim, yeni bir fırsat getirir; hazır olan kazançlı çıkar.',
    'döngünün bir aşaması kapanıyor; yeni sayfa açmak için uygun zaman.',
  ],
  'major_11_justice': [
    'dürüstlük ve denge vurgulanır; kararlarını net ve adil tut.',
    'bugün, yaptıklarının sonucu görünür olur; sorumluluk almak önemlidir.',
    'tartışmalarda adil ol; haklı olmak kadar hakkaniyet de değerlidir.',
    'sözlerin ve eylemlerin tutarlı olmalı; tutarlılık güven getirir.',
    'hesaplaşma zamanı; gerçekleri açıkça görmek rahatlatır.',
    'karar verirken duygudan çok dengeli değerlendirme işe yarar.',
    'sistemi ve kuralları hatırlatır; düzen, belirsizliği azaltır.',
    'dengeyi korursan sonuç lehine olur; net bir sınır çiz.',
  ],
  'major_12_hanged_man': [
    'beklemek ve bakış açısını değiştirmek gerekiyor; acele etmek çözüm getirmez.',
    'teslimiyet, kontrolsüzlük değil; farklı bir açıdan görmek için duraksama.',
    'şu an, hareket yerine içgörü zamanı; sabır yeni kapı açar.',
    'bir şeyi bırakınca rahatlayacağını söyler; tutunma, akışı tıkar.',
    'fedakarlık teması öne çıkar; küçük bir vazgeçiş büyük rahatlık getirir.',
    'duraklama, geri gitmek değildir; yeniden düzenleme fırsatı sunar.',
    'olaylara ters açıdan bak; bu, çözümü görünür kılar.',
    'görünmeyen bir ders var; onu fark etmek için yavaşlamak gerekiyor.',
  ],
  'major_13_death': [
    'bitiş ve dönüşüm zamanı; eski bir düzen kapanırken yenisi doğar.',
    'artık işe yaramayanı bırakman gerekiyor; bu, yenilenmeyi hızlandırır.',
    'değişim kaçınılmaz; direnmek yerine kabul etmek rahatlık getirir.',
    'bir döngü kapanıyor; yas tutmak doğal ama yeniye yer açmalısın.',
    'kökten bir dönüşüm teması var; yenilik için alan aç.',
    'eski alışkanlıkları bırakmanın zamanı; bu sayede hafiflersin.',
    'yenilenme için önce sadeleşmek gerekir; fazlalıkları temizle.',
    'değişim, korkutucu görünse de özgürlük getirir; dönüşüm seni güçlendirir.',
  ],
  'major_14_temperance': [
    'denge ve uyum arayışı vurgulanır; aşırılıkları yumuşatmak faydalı.',
    'sabırla karıştırılan şeyler daha iyi sonuç verir; yavaş ama sağlam ilerle.',
    'iki farklı şeyi birleştirmek mümkün; uyum, üçüncü bir yol yaratır.',
    'ölçülü davranmak bugün en doğru seçim; acele kararlar hata getirir.',
    'şifa ve iyileşme enerjisi var; kendine nazik davran.',
    'dengeli bir ritim kurarsan zihnin berraklaşır; rutin seni destekler.',
    'çatışan tarafları uzlaştır; orta yol, sürdürülebilir çözümdür.',
    'beden ve zihin dengesini kurmak önemli; küçük adımlar büyük etki yaratır.',
  ],
  'major_15_devil': [
    'bağlılık ve bağımlılık teması öne çıkar; zinciri görmek çözümün ilk adımı.',
    'tutku yüksek ama körleşme riski var; sınırlarını hatırla.',
    'fazla kontrol ya da takıntı yıpratır; esneklik özgürlük getirir.',
    'gölge yönlerle yüzleşme zamanı; onları inkâr etmek yerine fark et.',
    'kısa vadeli haz, uzun vadeli bedel getirebilir; seçimini bilinçle yap.',
    'bağımlı olduğun bir düzen var; onu gevşetmek rahatlama sağlar.',
    'çekim güçlü; ama kendi iradeni korumak önemli.',
    'kendini kısıtlayan bir inancı fark edersen, çözülme başlar.',
  ],
  'major_16_tower': [
    'ani bir farkındalık ya da kırılma gelebilir; bu, daha sağlam bir temele yol açar.',
    'yanlış yapıların yıkılması gerekiyor; gerçek, sarsıcı ama iyileştirici.',
    'beklenmedik bir gelişme planı değiştirir; esnek kalmak avantaj sağlar.',
    'eski bir inanç çatırdıyor; bırakmak, ilerlemeyi hızlandırır.',
    'kriz gibi görünen şey, özgürleşme fırsatı taşıyor; panik yerine netlik seç.',
    'yıkım, yeniden kurmanın başlangıcıdır; kalıcı olanı ayıkla.',
    'bugün, konfor alanı sarsılabilir; bu, gerçeklere yaklaşmanı sağlar.',
    'kontrolü kaybetmekten korkma; yeni düzen daha sağlam olabilir.',
  ],
  'major_17_star': [
    'umut ve ilham güçlü; yumuşak bir ışık, yolunu aydınlatıyor.',
    'iyileşme süreci hızlanıyor; sabırla ilerlersen ferahlık gelir.',
    'bugün, kalbini açtıkça fırsatlar çoğalır; güven duygusu artar.',
    'küçük bir dilek bile gerçek olabilir; niyetini netleştir.',
    'akışın içinde korunuyorsun; iç huzur, dış koşulları düzenler.',
    'ilham kaynağın yakın; küçük bir işaret bile yol gösterir.',
    'şifa ve tazelenme teması var; kendine iyi davran.',
    'geleceğe dair umut taşı; bu umut, adımlarını doğruya çeker.',
  ],
  'major_18_moon': [
    'belirsizlik ve sisli bir alan var; netlik için zamana ihtiyacın olabilir.',
    'sezgi yükseliyor ama kafa karışıklığı da artabilir; acele karar verme.',
    'gizli korkular yüzeye çıkıyor; onları fark etmek rahatlatır.',
    'yanılsamalar mümkün; gerçek ile varsayımı ayırmak gerekiyor.',
    'duygular dalgalı; bugün kendine nazik davranmak önemli.',
    'rüyalar ve semboller mesaj taşıyabilir; onları not etmek fayda sağlar.',
    'görünmeyen etkiler çalışıyor; sakin kalırsan tablo netleşir.',
    'şüpheyi bilgiyle dengele; araştırmak seni güvene taşır.',
  ],
  'major_19_sun': [
    'açıklık ve neşe enerjisi yükseliyor; görünür olmak başarı getirir.',
    'bugün, olumlu sonuçlar alma ihtimali yüksek; adımlarını net at.',
    'sıcaklık ve güven hissi var; ilişkilerde açıklık iyi gelir.',
    'gerçekler ortaya çıkıyor; bu, kararlarını kolaylaştırır.',
    'başarı ve kutlama teması öne çıkar; emeğinin karşılığı geliyor.',
    'kendine güven artıyor; bunu somut bir adımla destekle.',
    'güneş gibi parlamak mümkün; saklanmak yerine kendini göster.',
    'netlik, korkuyu dağıtır; ışık altında her şey daha anlaşılır.',
  ],
  'major_20_judgement': [
    'uyanış ve değerlendirme zamanı; geçmişin dersi geleceği belirler.',
    'bir çağrı hissedebilirsin; içten gelen bu sesi dinlemek önemli.',
    'kapanmamış bir konu tekrar gündeme gelebilir; bu kez net bir karar ver.',
    'kendini affetmek ve yeniden başlamak mümkün; yükleri bırak.',
    'hesaplaşma, temiz bir sayfa açar; gerçeklerle yüzleşmek özgürleştirir.',
    'yenilenme enerjisi güçlü; eskiyi bırakınca yeni yön belirginleşir.',
    'sorumluluk almak ve sonucu kabul etmek bugün güç verir.',
    'içsel bir çağrıya yanıt vermek, doğru yola hizalar.',
  ],
  'major_21_world': [
    'tamamlanma ve bütünlük teması var; bir döngü başarıyla kapanıyor.',
    'emeğinin karşılığını alma zamanı; sonuçlar kalıcı olabilir.',
    'bir sürecin sonuna geldin; yeni bir sayfa için hazır ol.',
    'düzen ve denge sağlanıyor; uyumlu bir kapanış mümkün.',
    'görünür başarı ve kutlama vurgulanır; kendini takdir et.',
    'bütün parçalar yerli yerine oturuyor; sabır meyve veriyor.',
    'uzun yolculuk tamamlanıyor; şimdi ödül toplama zamanı.',
    'sonuçlar net; bu tamamlanma, yeni bir başlangıcın temelidir.',
  ],
  'wands_ace': [
    'tutkunun kıvılcımını ve yeni bir işe başlama hevesini anlatır; enerjini toplaman yeterli.',
    'yaratıcı bir fikir filizleniyor; onu büyütmek için küçük bir adım at.',
    'ateş elementi harekete geçiyor; içindeki motivasyon seni ileri taşıyabilir.',
    'cesaret ve girişim vurgusu var; erteleme yerine başlamak güç verir.',
    'heyecanı yapılandırırsan sonuç alırsın; dağılmadan ilerle.',
    'bu kart, canlı bir başlangıç enerjisi taşır; bir projeyi ateşlemek için iyi zaman.',
    'kendi gücüne güven; inisiyatif almak kapıları açar.',
    'içindeki istek net; şimdi onu somut bir harekete dönüştür.',
  ],
  'wands_two': [
    'ufka bakma ve plan yapma zamanı; seçenekleri görüp net bir rota çiz.',
    'iki yol arasında kalabilirsin; kararını değerlerinle hizalamak rahatlatır.',
    'uzaktan görünen fırsatları değerlendirmek için küçük bir strateji kurmalısın.',
    'hırs ve merak var; ama acele yerine planlı ilerlemek daha güvenli.',
    'bugün, kontrol edebildiğin alanı genişletmek mümkün; ilk adımı düşün.',
    'kısa bir plan, büyük hedefe hizmet eder; yönünü netleştir.',
    'geçmiş deneyimlerin sana rehber; şimdi daha cesur bir seçim yapabilirsin.',
    'karar verme enerjisi güçlü; niyetini belirleyip harekete geç.',
  ],
  'wands_three': [
    'görüş alanın genişliyor; hazırladığın planın ilk sonuçları görünmeye başlıyor.',
    'işbirliği ve büyüme vurgusu var; doğru ortaklık ilerlemeyi hızlandırır.',
    'uzun vadeli hedefler netleşiyor; bugün küçük bir adım atmak yeterli.',
    'emeklerinin karşılığı ufukta; sabır ve istikrarla ilerle.',
    'yola çıkmışsın; şimdi yönü koruyup akışa güvenmek gerekiyor.',
    'gelişim fırsatı belirgin; küçük bir genişleme, büyük kapı açar.',
    'vizyonun net; bunu somut bir planla desteklemek önemli.',
    'ilerleme aşamasındasın; geriye değil ileriye bak.',
  ],
  'cups_ace': [
    'duygusal bir başlangıcın kapısı aralanıyor; kalbini açık tutmak şifa getirir.',
    'sevgi ve iç huzur artıyor; yeni bir bağ kurmak için uygun zaman.',
    'duyguların tazeleniyor; kendini ifade etmek yakınlığı artırır.',
    'kupa doluyor; sevgi akışı genişliyor ve şefkat güçleniyor.',
    'içsel dinginlik var; bunu bir paylaşım ya da yaratıcı ifade ile besle.',
    'kalp alanında temiz bir sayfa açılıyor; kırgınlığı bırakmak iyi gelir.',
    'duygusal açıklık yükseliyor; sevgiye yer açtıkça kolaylaşırsın.',
    'şefkatli bir yaklaşım bugün etkili; yumuşaklık bağları güçlendirir.',
  ],
  'cups_two': [
    'karşılıklı uyum ve eşitlik vurgulanır; bağını güçlendiren açık bir konuşma iyi gelir.',
    'iki kalbin dengesi öne çıkar; güveni büyütmek için ortak bir niyet belirle.',
    'ilişki teması güçlü; dürüst bir paylaşım yakınlığı artırır.',
    'birlikte hareket etmek kolaylaşıyor; ortak hedefler sizi bir arada tutar.',
    'duygusal denge kurulur; küçük bir uzlaşma büyük rahatlık getirir.',
    'karşılıklılık önemli; tek taraflı yükü azaltmak gerek.',
    'bu kart, dostluk ya da aşk bağında uyumu gösterir; sıcak bir adım at.',
    'kalpten bir teklif ya da barışma enerjisi var; nazik ol.',
  ],
  'cups_three': [
    'kutlama ve paylaşım zamanı; yakın çevreyle bir araya gelmek seni yükseltir.',
    'sosyal bağlar güçleniyor; destek almak ve vermek bugün çok faydalı.',
    'neşe ve birliktelik vurgusu var; küçük bir buluşma bile enerji getirir.',
    'işbirliği ve dayanışma artıyor; ortak sevinç moralini yükseltir.',
    'duygusal destek hattı açık; bir arkadaşla konuşmak iyi gelebilir.',
    'sevinçli bir gelişme yakın; bunu paylaşmak daha anlamlı kılar.',
    'topluluk içinde görünür olmak güven getirir; yalnız kalma ihtiyacını azalt.',
    'birlikte üretmek ya da kutlamak için uygun zaman; hafiflik iyileştirir.',
  ],
  'swords_ace': [
    'zihinsel netlik geliyor; gerçeği görüp keskin bir karar almak mümkün.',
    'düşünceler berraklaşıyor; gereksiz karmaşa dağılabilir.',
    'doğruyu söylemek ve gerçeği savunmak bugün önemli; netlik güç verir.',
    'fikirler keskinleşiyor; tek bir net cümle süreci değiştirir.',
    'adalet ve dürüstlük vurgusu var; açık olmak rahatlatır.',
    'zihin gücü artıyor; kararlarını verilerle desteklemek faydalı.',
    'kafa karışıklığı çözülüyor; net bir tercih, ilerlemeyi hızlandırır.',
    'gerçekleri görmek can acıtabilir ama özgürleştirir; cesur ol.',
  ],
  'swords_three': [
    'kalpte bir kırılma ya da hayal kırıklığı teması var; duyguyu kabul etmek iyileştirir.',
    'acı veren bir gerçek görünür olabilir; gerçeği görmek uzun vadede rahatlık getirir.',
    'duygusal bir çatışma yaşanıyor; kendine şefkat göstermek önemli.',
    'geçmiş bir kırgınlık su yüzüne çıkabilir; konuşmak yarayı hafifletir.',
    'zihin ve kalp arasında bir gerilim var; netlik, iyileşmeyi başlatır.',
    'acı, dürüstlüğün bedeli olabilir; bu süreçte yavaşlamak iyi gelir.',
    'kırgınlığı bastırmak yerine ifade etmek, şifayı hızlandırır.',
    'bu kart, kalbi temizleyen bir gerçekle yüzleşmeyi anlatır; ardından ferahlama gelir.',
  ],
  'pentacles_ace': [
    'maddi bir başlangıç enerjisi var; somut bir fırsatı değerlendirmek için uygun zaman.',
    'toprak elementi güçleniyor; emeklerinin karşılığını almak mümkün.',
    'güvenli bir temel atma zamanı; küçük bir yatırım büyüme getirir.',
    'maddi alanda yeni bir kapı açılıyor; planlı adım başarı sağlar.',
    'somut sonuçlar görünmeye başlıyor; düzenli çalışma destek olur.',
    'kaynaklarını artırmak için şanslı bir dönem; fırsatı kaçırma.',
    'pratik adımlar önem kazanır; bugün attığın tohumlar büyür.',
    'maddi istikrar için niyet oluştur; istikrar küçük alışkanlıklarla kurulur.',
  ],
  'pentacles_three': [
    'emek ve ustalık vurgulanır; işi iyi yapman takdir getirir.',
    'ekip çalışması güçleniyor; ortak hedefle ilerlemek daha verimli.',
    'becerilerini gösterme zamanı; detaylara özen başarıyı artırır.',
    'planlı iş birliği ve uzmanlık öne çıkar; öğrenmeye açık ol.',
    'somut sonuçlar için birlikte hareket etmek gerekiyor; dayanışma kazandırır.',
    'ustalık geliştikçe güven artar; küçük bir iyileştirme bile değerli.',
    'yaptığın işe sadık kalırsan sonuç büyür; disiplin seni destekler.',
    'kendi payını netleştir; rolün belirginleşince süreç hızlanır.',
  ],
};
// TODO: Kalan minor arkana kartları için kart özel satırlar ekleyin.
